# Generated by Django 5.0.2 on 2024-02-13 05:26

import django.db.models.deletion
import django.utils.timezone
import educativeoffer.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=180)),
                ('periodo', models.IntegerField(blank=True, help_text='Periodo de la carrera al que pertenece la asignatura', null=True)),
                ('habilitada', models.BooleanField(default=True, help_text='Habilitar o deshabilitar las asignaturas', null=True)),
            ],
            options={
                'verbose_name_plural': 'Asignaturas',
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('disponible', models.BooleanField(default=True, help_text='Desmarcar para que no aparezca en la notificaciones.')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Avisos',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=350)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=educativeoffer.models.custom_upload_to_es)),
                ('division', models.CharField(blank=True, choices=[('4', 'Cuartrimestre'), ('6', 'Semestre')], help_text='Meses de duración de cada periodo', max_length=1, null=True)),
                ('num_periodo', models.IntegerField(blank=True, help_text='El número de periodos que consta la carrera', null=True)),
            ],
            options={
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigoPostal', models.IntegerField(default=0, verbose_name=5)),
            ],
            options={
                'verbose_name_plural': 'Localidades',
            },
        ),
        migrations.CreateModel(
            name='MedioContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Medios de Contacto',
            },
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=6, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Sexos',
            },
        ),
        migrations.CreateModel(
            name='Valor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Valores',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre', models.CharField(max_length=50)),
                ('apellidoPaterno', models.CharField(max_length=50)),
                ('apellidoMaterno', models.CharField(max_length=50)),
                ('fechaNacimiento', models.DateField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('calle', models.CharField(max_length=100)),
                ('n_int', models.IntegerField()),
                ('n_ext', models.IntegerField()),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('activation_key', models.CharField(blank=True, max_length=40)),
                ('key_expires', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, related_name='user_groups', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='user_permissions', to='auth.permission')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.localidad')),
                ('sexo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.sexo')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('matricula', models.CharField(help_text='Mátricula única para el alumno', max_length=12, primary_key=True, serialize=False, unique=True)),
                ('status', models.BooleanField(default=True, help_text='En caso de dar de baja al alumno, desmarcar')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('medioContacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.mediocontacto')),
            ],
            options={
                'verbose_name_plural': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='AsesorEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=45, unique=True)),
                ('grado_academico', models.CharField(choices=[('Licenciatura', 'Licenciatura'), ('Maestría', 'Maestría'), ('Doctorado', 'Doctorado')], max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.especialidad')),
            ],
            options={
                'verbose_name_plural': 'Asesores Educativos',
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
                ('uploadedFile', models.FileField(upload_to=educativeoffer.models.custom_upload_to_do)),
                ('dateTimeOfUpload', models.DateTimeField(auto_now=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.asignatura')),
            ],
            options={
                'verbose_name_plural': 'Documentos',
            },
        ),
        migrations.AddField(
            model_name='asignatura',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaturas', to='educativeoffer.especialidad'),
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=educativeoffer.models.custom_upload_to_ga)),
                ('habilitada', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.categoria')),
            ],
            options={
                'verbose_name_plural': 'Galería',
            },
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField(unique=True)),
                ('aceptada', models.BooleanField(default=False)),
                ('periodo', models.CharField(max_length=7)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.alumno')),
                ('asesor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.asesoreducativo')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.especialidad')),
            ],
            options={
                'verbose_name_plural': 'Inscripciones',
            },
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=20)),
                ('numero', models.IntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username_facebook', models.CharField(max_length=128, unique=True)),
                ('username_instagram', models.CharField(max_length=128, unique=True)),
                ('username_twitter', models.CharField(max_length=128, unique=True)),
                ('username_youtube', models.CharField(max_length=128, unique=True)),
                ('mision', models.CharField(max_length=300, unique=True)),
                ('vision', models.CharField(max_length=300, unique=True)),
                ('telefonos', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.localidad')),
            ],
            options={
                'verbose_name_plural': 'Datos de la escuela',
            },
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('receptor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_recibidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.estado')),
            ],
            options={
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.AddField(
            model_name='localidad',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.municipio'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=educativeoffer.models.custom_upload_to)),
                ('bio', models.TextField(blank=True, max_length=128, null=True)),
                ('username_facebook', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('username_instagram', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('username_twitter', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('username_youtube', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfiles',
            },
        ),
        migrations.CreateModel(
            name='ProyectoAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('instrucciones', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.asesoreducativo')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.especialidad')),
            ],
            options={
                'verbose_name_plural': 'Asignación de Proyectos',
            },
        ),
        migrations.CreateModel(
            name='ProyectoFinal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('documento_pdf', models.FileField(upload_to=educativeoffer.models.custom_upload_to_pf)),
                ('aprobado', models.BooleanField(default=False)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.alumno')),
                ('proyecto_asignado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.proyectoasignacion')),
            ],
            options={
                'verbose_name_plural': 'Proyectos Finales',
                'unique_together': {('alumno', 'proyecto_asignado')},
            },
        ),
        migrations.CreateModel(
            name='ImagenProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to=educativeoffer.models.custom_upload_to_pi)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.proyectofinal')),
            ],
            options={
                'verbose_name_plural': 'Imágenes de Proyectos Finales',
            },
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(unique=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Teléfonos',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=7)),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.alumno')),
                ('asesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.asesoreducativo')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.asignatura')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
                'unique_together': {('asesor', 'alumno', 'asignatura')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='asignatura',
            unique_together={('nombre', 'especialidad', 'periodo')},
        ),
        migrations.CreateModel(
            name='ProyectoAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.alumno')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='educativeoffer.proyectoasignacion')),
            ],
            options={
                'verbose_name_plural': 'Relación Proyectos - Alumno',
                'unique_together': {('proyecto', 'alumno')},
            },
        ),
    ]
